version: '3.4'

services:
  
  bookapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:443;http://+:80
      - "ConnectionStrings:BookConnection=Server=booksqldb;Database=Books;User Id=sa;Password=Lf12345!"
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  booksqldb:
    container_name: booksqldb
    ports:
      - "1433:1433" 
    environment:
      SA_PASSWORD: "Lf12345!"
      ACCEPT_EULA: "Y"